name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Set up Java (required for HTML validator)
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ~/validator
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install wget (for HTML validator download)
    - name: Install wget
      run: sudo apt-get install -y wget

    # HTML validation (most reliable method)
    - name: Validate HTML
      run: |
        mkdir -p ~/validator
        wget https://github.com/validator/validator/releases/latest/download/vnu.linux.zip -O ~/validator/vnu.zip
        unzip ~/validator/vnu.zip -d ~/validator
        java -jar ~/validator/dist/vnu.jar --skip-non-html --errors-only index.html

    # CSS validation
    - name: Validate CSS
      run: |
        npm install -g css-validator
        css-validator style.css

    # JavaScript linting
    - name: Lint JavaScript
      uses: github/super-linter@v4
      env:
        VALIDATE_JAVASCRIPT_ES: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Security scanning
    - name: Run ESLint security audit
      run: npx eslint-plugin-security .

    # Dependency vulnerability scanning
    - name: Audit npm packages
      run: npm audit

    # Quality gate for vulnerabilities
    - name: Check for vulnerabilities
      if: ${{ failure() && steps.audit.outcome == 'failure' }}
      run: exit 1

  deploy:
    needs: quality-checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        scope: ${{ secrets.VERCEL_ORG_ID }}
